### ISSUE TITLE
Enhancement: Set location of Timer Bars

### ISSUE THREAD

**Issue by bmk-dev** [alexguirre/RAGENativeUI#138]
Wondering if it would be possible to allow us to set the location of timer bars on screen? The bottom right is often covered by the player's ELS UI, if they're using it.

**Comment by alexguirre** [comment]
Do you want it as part of the API or as some configuration that affects all plugins using RNUI? For the API, you can use `TimerBarBase.Draw(x, y);` directly instead of the `TimerBarPool`, though `TimerBarPool` already does quite a bit to avoid overlapping between different plugins and the game scripts.

**Comment by bmk-dev** [comment]
`TimerBarBase.Draw(x, y);` will actually fit my purpose. I didn't realize the base class had a method for drawing the bars individually, probably should have checked first! Appreciate the response.

**Comment by alexguirre** [comment]
In that case you will need to at least request the `timerbars` texture dictionary before drawing them and maybe do some of the `RESET/SET_SCRIPT_GFX_ALIGN_*` stuff (so the timerbars are affected by the safezone borders) depending on how you want to draw them.
https://github.com/alexguirre/RAGENativeUI/blob/e390ba652268169480296795290e37a6fb207677/Source/Elements/TimerBars/TimerBarPool.cs#L27-L34

**Comment by bmk-dev** [comment]
Sounds good, I'll have play around with it! Thanks for the help.
